--------------------------------------------------------
--  File created - Saturday-April-18-2026   
--------------------------------------------------------
DROP SEQUENCE "ATELIER"."MACHINE_SEQ";
DROP SEQUENCE "ATELIER"."SEQ_CLIENT";
DROP SEQUENCE "ATELIER"."SEQ_COMMANDE";
DROP SEQUENCE "ATELIER"."SEQ_EMPLOYE";
DROP SEQUENCE "ATELIER"."SEQ_MATERIAU";
DROP SEQUENCE "ATELIER"."SEQ_POINTAGE_EMPLOYE";
DROP SEQUENCE "ATELIER"."SEQ_VISITE_CLIENT";
DROP TABLE "ATELIER"."CLIENT" cascade constraints;
DROP TABLE "ATELIER"."COMMANDE" cascade constraints;
DROP TABLE "ATELIER"."EMPLOYE" cascade constraints;
DROP TABLE "ATELIER"."MACHINE" cascade constraints;
DROP TABLE "ATELIER"."MATERIAU" cascade constraints;
DROP TABLE "ATELIER"."POINTAGE_EMPLOYE" cascade constraints;
DROP TABLE "ATELIER"."UTILISER" cascade constraints;
DROP TABLE "ATELIER"."VISITE_CLIENT" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence MACHINE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATELIER"."MACHINE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENT
--------------------------------------------------------

   CREATE SEQUENCE  "ATELIER"."SEQ_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMANDE
--------------------------------------------------------

   CREATE SEQUENCE  "ATELIER"."SEQ_COMMANDE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYE
--------------------------------------------------------

   CREATE SEQUENCE  "ATELIER"."SEQ_EMPLOYE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MATERIAU
--------------------------------------------------------

   CREATE SEQUENCE  "ATELIER"."SEQ_MATERIAU"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POINTAGE_EMPLOYE
--------------------------------------------------------

   CREATE SEQUENCE  "ATELIER"."SEQ_POINTAGE_EMPLOYE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_VISITE_CLIENT
--------------------------------------------------------

   CREATE SEQUENCE  "ATELIER"."SEQ_VISITE_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ATELIER"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADDRESSE" VARCHAR2(255 BYTE), 
	"SOCIETE" VARCHAR2(150 BYTE), 
	"MATRICULE_FISCALE" VARCHAR2(50 BYTE), 
	"N_CIN" VARCHAR2(20 BYTE), 
	"SITE_WEB_FB" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "ATELIER"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER, 
	"DATE_COMMANDE" DATE DEFAULT sysdate, 
	"DETAILS_COMMANDE" VARCHAR2(500 BYTE), 
	"DIMENSIONS" VARCHAR2(100 BYTE), 
	"PRIX" NUMBER(10,2), 
	"ETAT" VARCHAR2(20 BYTE), 
	"ID_CLIENT" NUMBER, 
	"ID_EMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "ATELIER"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER, 
	"CIN" VARCHAR2(100 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"POSTE" VARCHAR2(100 BYTE), 
	"SALAIRE" NUMBER(10,2), 
	"DISPONIBILTE" VARCHAR2(20 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATE_EMBAUCHE" DATE DEFAULT sysdate, 
	"ADRESSE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINE
--------------------------------------------------------

  CREATE TABLE "ATELIER"."MACHINE" 
   (	"ID_MACHINE" NUMBER, 
	"REFERENCE" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"ETAT" VARCHAR2(30 BYTE), 
	"DATE_DERNIERE_MAINTNANCE" DATE, 
	"HEURES_UTILISATION" NUMBER(10,2), 
	"QUANTITE" NUMBER(10,0), 
	"ID_EMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIAU
--------------------------------------------------------

  CREATE TABLE "ATELIER"."MATERIAU" 
   (	"ID_MATERIAU" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"QUANTITE" NUMBER(10,2), 
	"PRIX_ACHAT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POINTAGE_EMPLOYE
--------------------------------------------------------

  CREATE TABLE "ATELIER"."POINTAGE_EMPLOYE" 
   (	"ID_POINTAGE" NUMBER, 
	"CIN" VARCHAR2(8 BYTE), 
	"ACTION" VARCHAR2(3 BYTE), 
	"DATE_POINTAGE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISER
--------------------------------------------------------

  CREATE TABLE "ATELIER"."UTILISER" 
   (	"ID_COMMANDE" NUMBER, 
	"ID_MATERIAU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VISITE_CLIENT
--------------------------------------------------------

  CREATE TABLE "ATELIER"."VISITE_CLIENT" 
   (	"ID_VISITE" NUMBER, 
	"CIN_CLIENT" VARCHAR2(8 BYTE), 
	"TYPE_VISITE" VARCHAR2(20 BYTE), 
	"DATE_VISITE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ATELIER.CLIENT
SET DEFINE OFF;
REM INSERTING into ATELIER.COMMANDE
SET DEFINE OFF;
Insert into ATELIER.COMMANDE (ID_COMMANDE,DATE_COMMANDE,DETAILS_COMMANDE,DIMENSIONS,PRIX,ETAT,ID_CLIENT,ID_EMPLOYE) values (1001,to_date('03-MAR-26','DD-MON-RR'),'fragile','14x20x15 cm',100,'? Terminée',null,null);
Insert into ATELIER.COMMANDE (ID_COMMANDE,DATE_COMMANDE,DETAILS_COMMANDE,DIMENSIONS,PRIX,ETAT,ID_CLIENT,ID_EMPLOYE) values (1005,to_date('03-MAR-26','DD-MON-RR'),'fragile','14x20x15 cm',200,'? Terminée',null,null);
Insert into ATELIER.COMMANDE (ID_COMMANDE,DATE_COMMANDE,DETAILS_COMMANDE,DIMENSIONS,PRIX,ETAT,ID_CLIENT,ID_EMPLOYE) values (1006,to_date('12-JAN-00','DD-MON-RR'),'SAC MN BERSHKA','15x30x12 cm',200,'? En cours',null,null);
Insert into ATELIER.COMMANDE (ID_COMMANDE,DATE_COMMANDE,DETAILS_COMMANDE,DIMENSIONS,PRIX,ETAT,ID_CLIENT,ID_EMPLOYE) values (1560,to_date('01-JAN-00','DD-MON-RR'),'dsqqqqqssssss','4x2x3 cm',0,'? Livrée',null,null);
Insert into ATELIER.COMMANDE (ID_COMMANDE,DATE_COMMANDE,DETAILS_COMMANDE,DIMENSIONS,PRIX,ETAT,ID_CLIENT,ID_EMPLOYE) values (1,to_date('01-JAN-00','DD-MON-RR'),'bla ablablablalblba','5x5x3 cm',100,'? Terminée',null,null);
Insert into ATELIER.COMMANDE (ID_COMMANDE,DATE_COMMANDE,DETAILS_COMMANDE,DIMENSIONS,PRIX,ETAT,ID_CLIENT,ID_EMPLOYE) values (21,to_date('01-JAN-00','DD-MON-RR'),'blassssssssssssssssss','6x9x4 cm',30,'? Terminée',null,null);
REM INSERTING into ATELIER.EMPLOYE
SET DEFINE OFF;
Insert into ATELIER.EMPLOYE (ID_EMPLOYE,CIN,NOM,POSTE,SALAIRE,DISPONIBILTE,TELEPHONE,EMAIL,DATE_EMBAUCHE,ADRESSE) values (43,'11467555','khaaalil','Service client',2500,'en congé','93018000','kbair@gmail.com',to_date('06-APR-26','DD-MON-RR'),'bizerte');
Insert into ATELIER.EMPLOYE (ID_EMPLOYE,CIN,NOM,POSTE,SALAIRE,DISPONIBILTE,TELEPHONE,EMAIL,DATE_EMBAUCHE,ADRESSE) values (22,'11467256','chrichi','Responsable Atelier',400000,'en congé','95410220','cherichiyoussef05@gmail.com',to_date('01-JAN-99','DD-MON-RR'),'fi tunis');
Insert into ATELIER.EMPLOYE (ID_EMPLOYE,CIN,NOM,POSTE,SALAIRE,DISPONIBILTE,TELEPHONE,EMAIL,DATE_EMBAUCHE,ADRESSE) values (26,'11467251','kbaier','Service client',200,'disponible','93018000','kbaier@gmail.com',to_date('01-JAN-00','DD-MON-RR'),'bizerte');
REM INSERTING into ATELIER.MACHINE
SET DEFINE OFF;
REM INSERTING into ATELIER.MATERIAU
SET DEFINE OFF;
Insert into ATELIER.MATERIAU (ID_MATERIAU,NOM,TYPE,QUANTITE,PRIX_ACHAT) values (1,'planche','Colle',30,20);
Insert into ATELIER.MATERIAU (ID_MATERIAU,NOM,TYPE,QUANTITE,PRIX_ACHAT) values (2,'woods','Bois',2,1);
Insert into ATELIER.MATERIAU (ID_MATERIAU,NOM,TYPE,QUANTITE,PRIX_ACHAT) values (3,'planche','Clou',22,17);
REM INSERTING into ATELIER.POINTAGE_EMPLOYE
SET DEFINE OFF;
Insert into ATELIER.POINTAGE_EMPLOYE (ID_POINTAGE,CIN,ACTION,DATE_POINTAGE) values (1,'11470504','IN',to_timestamp('14-APR-26 02.48.31.208000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ATELIER.POINTAGE_EMPLOYE (ID_POINTAGE,CIN,ACTION,DATE_POINTAGE) values (2,'11467555','IN',to_timestamp('14-APR-26 04.21.58.713000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ATELIER.POINTAGE_EMPLOYE (ID_POINTAGE,CIN,ACTION,DATE_POINTAGE) values (3,'11467555','OUT',to_timestamp('14-APR-26 04.23.26.423000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ATELIER.POINTAGE_EMPLOYE (ID_POINTAGE,CIN,ACTION,DATE_POINTAGE) values (4,'11467555','IN',to_timestamp('14-APR-26 11.20.29.827000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into ATELIER.UTILISER
SET DEFINE OFF;
REM INSERTING into ATELIER.VISITE_CLIENT
SET DEFINE OFF;
Insert into ATELIER.VISITE_CLIENT (ID_VISITE,CIN_CLIENT,TYPE_VISITE,DATE_VISITE) values (1,'11467258','DEVIS',to_timestamp('14-APR-26 02.48.31.215000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
--------------------------------------------------------
--  DDL for Index UK_MACHINE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."UK_MACHINE" ON "ATELIER"."MACHINE" ("ID_MACHINE", "REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."UK_EMPLOYE" ON "ATELIER"."EMPLOYE" ("ID_EMPLOYE", "CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."PK_EMPLOYE" ON "ATELIER"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MACHINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."MACHINE_PK" ON "ATELIER"."MACHINE" ("ID_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."COMMANDE_PK" ON "ATELIER"."COMMANDE" ("ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."UK_CLIENT" ON "ATELIER"."CLIENT" ("ID_CLIENT", "N_CIN", "MATRICULE_FISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UTILISER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."UTILISER_PK" ON "ATELIER"."UTILISER" ("ID_COMMANDE", "ID_MATERIAU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."CLIENT_PK" ON "ATELIER"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIAU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATELIER"."MATERIAU_PK" ON "ATELIER"."MATERIAU" ("ID_MATERIAU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MACHINE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATELIER"."MACHINE_TRG" 
BEFORE INSERT ON MACHINE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ATELIER"."MACHINE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CLIENT_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATELIER"."TRG_CLIENT_ID" 
BEFORE INSERT ON ATELIER.CLIENT
FOR EACH ROW
BEGIN
  IF :NEW.ID_CLIENT IS NULL THEN
    :NEW.ID_CLIENT := ATELIER.SEQ_CLIENT.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "ATELIER"."TRG_CLIENT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_COMMANDE_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATELIER"."TRG_COMMANDE_ID" 
BEFORE INSERT ON ATELIER.COMMANDE
FOR EACH ROW
BEGIN
  IF :NEW.ID_COMMANDE IS NULL THEN
    :NEW.ID_COMMANDE := ATELIER.SEQ_COMMANDE.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "ATELIER"."TRG_COMMANDE_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMPLOYE_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATELIER"."TRG_EMPLOYE_ID" 
BEFORE INSERT ON ATELIER.EMPLOYE
FOR EACH ROW
BEGIN
  IF :NEW.ID_EMPLOYE IS NULL THEN
    :NEW.ID_EMPLOYE := ATELIER.SEQ_EMPLOYE.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "ATELIER"."TRG_EMPLOYE_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MATERIAU_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATELIER"."TRG_MATERIAU_ID" 
BEFORE INSERT ON ATELIER.MATERIAU
FOR EACH ROW
BEGIN
  IF :NEW.ID_MATERIAU IS NULL THEN
    SELECT ATELIER.SEQ_MATERIAU.NEXTVAL
    INTO :NEW.ID_MATERIAU
    FROM dual;
  END IF;
END;

/
ALTER TRIGGER "ATELIER"."TRG_MATERIAU_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_POINTAGE_EMPLOYE_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATELIER"."TRG_POINTAGE_EMPLOYE_BI" 
BEFORE INSERT ON ATELIER.POINTAGE_EMPLOYE
FOR EACH ROW
BEGIN
  IF :NEW.ID_POINTAGE IS NULL THEN
    SELECT ATELIER.SEQ_POINTAGE_EMPLOYE.NEXTVAL INTO :NEW.ID_POINTAGE FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "ATELIER"."TRG_POINTAGE_EMPLOYE_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_VISITE_CLIENT_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATELIER"."TRG_VISITE_CLIENT_BI" 
BEFORE INSERT ON ATELIER.VISITE_CLIENT
FOR EACH ROW
BEGIN
  IF :NEW.ID_VISITE IS NULL THEN
    SELECT ATELIER.SEQ_VISITE_CLIENT.NEXTVAL INTO :NEW.ID_VISITE FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "ATELIER"."TRG_VISITE_CLIENT_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "ATELIER"."COMMANDE" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "ATELIER"."EMPLOYE" ADD CONSTRAINT "CHK_EMP_EMAIL" CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@gmail\.com$')) ENABLE NOVALIDATE;
  ALTER TABLE "ATELIER"."EMPLOYE" ADD CONSTRAINT "CHK_EMP_NOM" CHECK (REGEXP_LIKE(NOM, '^[A-Za-zÀ-ÿ[:space:]]+$')) ENABLE;
  ALTER TABLE "ATELIER"."EMPLOYE" ADD CONSTRAINT "CHK_EMP_TEL" CHECK (REGEXP_LIKE(TELEPHONE, '^[0-9]{8}$')) ENABLE;
  ALTER TABLE "ATELIER"."EMPLOYE" ADD CONSTRAINT "CHK_EMP_CIN" CHECK (REGEXP_LIKE(CIN, '^[0-9]{8}$')) ENABLE;
  ALTER TABLE "ATELIER"."EMPLOYE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."EMPLOYE" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."EMPLOYE" ADD CONSTRAINT "PK_EMPLOYE" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATELIER"."EMPLOYE" ADD CONSTRAINT "UK_EMPLOYE" UNIQUE ("ID_EMPLOYE", "CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "ATELIER"."MACHINE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."MACHINE" MODIFY ("ID_MACHINE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."MACHINE" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."MACHINE" ADD CONSTRAINT "MACHINE_PK" PRIMARY KEY ("ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATELIER"."MACHINE" ADD CONSTRAINT "UK_MACHINE" UNIQUE ("ID_MACHINE", "REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIAU
--------------------------------------------------------

  ALTER TABLE "ATELIER"."MATERIAU" MODIFY ("ID_MATERIAU" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."MATERIAU" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."MATERIAU" ADD CONSTRAINT "MATERIAU_PK" PRIMARY KEY ("ID_MATERIAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VISITE_CLIENT
--------------------------------------------------------

  ALTER TABLE "ATELIER"."VISITE_CLIENT" ADD PRIMARY KEY ("ID_VISITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATELIER"."VISITE_CLIENT" MODIFY ("DATE_VISITE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."VISITE_CLIENT" MODIFY ("TYPE_VISITE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."VISITE_CLIENT" MODIFY ("CIN_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "ATELIER"."UTILISER" ADD CONSTRAINT "UTILISER_PK" PRIMARY KEY ("ID_COMMANDE", "ID_MATERIAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATELIER"."UTILISER" MODIFY ("ID_MATERIAU" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."UTILISER" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINTAGE_EMPLOYE
--------------------------------------------------------

  ALTER TABLE "ATELIER"."POINTAGE_EMPLOYE" ADD PRIMARY KEY ("ID_POINTAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATELIER"."POINTAGE_EMPLOYE" ADD CHECK (ACTION IN ('IN','OUT')) ENABLE;
  ALTER TABLE "ATELIER"."POINTAGE_EMPLOYE" MODIFY ("DATE_POINTAGE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."POINTAGE_EMPLOYE" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."POINTAGE_EMPLOYE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CHK_CLT_MF" CHECK (REGEXP_LIKE(MATRICULE_FISCALE, '^[0-9]{7}[A-Z]/[0-9]{9}/[A-Z]$')) ENABLE NOVALIDATE;
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CHK_CLT_SITE" CHECK (SITE_WEB_FB IS NULL OR REGEXP_LIKE(SITE_WEB_FB, '\.com$')) ENABLE;
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CHK_CLT_CIN" CHECK (REGEXP_LIKE(N_CIN, '^[0-9]{8}$')) ENABLE;
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CHK_CLT_EMAIL" CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@gmail\.com$')) ENABLE;
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CHK_CLT_TEL" CHECK (REGEXP_LIKE(TELEPHONE, '^[0-9]{8}$')) ENABLE;
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CHK_CLT_PRENOM" CHECK (REGEXP_LIKE(PRENOM, '^[A-Za-zÀ-ÿ[:space:]]+$')) ENABLE;
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CHK_CLT_NOM" CHECK (REGEXP_LIKE(NOM, '^[A-Za-zÀ-ÿ[:space:]]+$')) ENABLE;
  ALTER TABLE "ATELIER"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATELIER"."CLIENT" MODIFY ("MATRICULE_FISCALE" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."CLIENT" MODIFY ("N_CIN" NOT NULL ENABLE);
  ALTER TABLE "ATELIER"."CLIENT" ADD CONSTRAINT "UK_CLIENT" UNIQUE ("ID_CLIENT", "N_CIN", "MATRICULE_FISCALE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "ATELIER"."COMMANDE" ADD CONSTRAINT "FKK_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "ATELIER"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "ATELIER"."COMMANDE" ADD CONSTRAINT "FK_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "ATELIER"."CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "ATELIER"."MACHINE" ADD CONSTRAINT "FK_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "ATELIER"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "ATELIER"."UTILISER" ADD CONSTRAINT "FK_COMMANDE" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "ATELIER"."COMMANDE" ("ID_COMMANDE") ENABLE;
  ALTER TABLE "ATELIER"."UTILISER" ADD CONSTRAINT "FK_MATERIAU" FOREIGN KEY ("ID_MATERIAU")
	  REFERENCES "ATELIER"."MATERIAU" ("ID_MATERIAU") ENABLE;

--------------------------------------------------------
--  PATCH METIERS AVANCES (safe post-export)
--------------------------------------------------------

-- Ajouter SEUIL_ALERTE si la colonne n'existe pas
DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM ALL_TAB_COLUMNS
  WHERE OWNER = 'ATELIER'
    AND TABLE_NAME = 'MATERIAU'
    AND COLUMN_NAME = 'SEUIL_ALERTE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ATELIER.MATERIAU ADD (SEUIL_ALERTE NUMBER(10,2))';
  END IF;
END;
/

-- Initialiser le seuil pour les lignes existantes
UPDATE ATELIER.MATERIAU
SET SEUIL_ALERTE = CASE
  WHEN QUANTITE IS NULL OR QUANTITE <= 0 THEN 5
  ELSE GREATEST(5, ROUND(QUANTITE * 0.30, 2))
END
WHERE SEUIL_ALERTE IS NULL;

-- Contrainte de validite (idempotente)
DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM ALL_CONSTRAINTS
  WHERE OWNER = 'ATELIER'
    AND TABLE_NAME = 'MATERIAU'
    AND CONSTRAINT_NAME = 'CHK_MAT_SEUIL_NONNEG';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ATELIER.MATERIAU ADD CONSTRAINT CHK_MAT_SEUIL_NONNEG CHECK (SEUIL_ALERTE IS NULL OR SEUIL_ALERTE >= 0) ENABLE';
  END IF;
END;
/

-- Index pour accelerer la prevision sur DATE_COMMANDE
DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM ALL_INDEXES
  WHERE OWNER = 'ATELIER'
    AND INDEX_NAME = 'IDX_COMMANDE_DATE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ATELIER.IDX_COMMANDE_DATE ON ATELIER.COMMANDE (DATE_COMMANDE)';
  END IF;
END;
/

COMMIT;
